# Generated by Django 4.1.1 on 2022-09-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('publishyear', models.IntegerField()),
                ('genre', models.CharField(max_length=255)),
            ],
        ),
    ]
